import Foundation
import UIKit
import PDFKit

/// PRD — Pet Vault travel paperwork. Generates a PDF summary containing pet
/// identity, selected documents, and owner contact for domestic or
/// international travel.
enum TravelPaperworkService {
    struct TravelContext {
        let pet: Pet
        let documents: [PetDocument]
        let ownerName: String
        let ownerPhone: String
        let ownerEmail: String
        let destination: String
        let isInternational: Bool
        let departureDate: Date
    }

    /// Generates a travel PDF and returns its temporary file URL.
    static func generatePDF(context: TravelContext) -> URL? {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium

        let pdfMeta: [String: Any] = [
            kCGPDFContextCreator as String: "Pawly Pet Vault",
            kCGPDFContextTitle as String: "Travel Paperwork – \(context.pet.name)"
        ]

        let tempURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("Pawly_Travel_\(context.pet.name)_\(Int(Date().timeIntervalSince1970)).pdf")

        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMeta
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: 612, height: 792), format: format)

        do {
            try renderer.writePDF(to: tempURL) { contextPDF in
                contextPDF.beginPage()
                var cursor: CGFloat = 60

                // Header
                drawText("Pawly Travel Paperwork", at: cursor, font: .systemFont(ofSize: 24, weight: .bold), align: .center)
                cursor += 36
                drawText("Generated on \(formatter.string(from: .now))", at: cursor, font: .systemFont(ofSize: 12), color: .darkGray, align: .center)
                cursor += 40

                // Pet info
                drawSection("Pet Information", at: &cursor)
                drawLine("Name: \(context.pet.name)", at: &cursor)
                drawLine("Species: \(context.pet.species.displayName)", at: &cursor)
                drawLine("Breed: \(context.pet.breed.isEmpty ? "Mixed" : context.pet.breed)", at: &cursor)
                drawLine("Age: \(context.pet.ageDescription)", at: &cursor)
                drawLine("Sex: \(context.pet.sex.displayName)", at: &cursor)
                if let weight = context.pet.weightKg {
                    drawLine("Weight: \(weight) kg", at: &cursor)
                }
                cursor += 8

                // Owner info
                drawSection("Owner Contact", at: &cursor)
                drawLine("Name: \(context.ownerName)", at: &cursor)
                drawLine("Phone: \(context.ownerPhone)", at: &cursor)
                drawLine("Email: \(context.ownerEmail)", at: &cursor)
                cursor += 8

                // Travel details
                drawSection("Travel Details", at: &cursor)
                drawLine("Destination: \(context.destination)", at: &cursor)
                drawLine("Type: \(context.isInternational ? "International" : "Domestic")", at: &cursor)
                drawLine("Departure: \(formatter.string(from: context.departureDate))", at: &cursor)
                cursor += 8

                // Documents
                drawSection("Attached Documents", at: &cursor)
                if context.documents.isEmpty {
                    drawLine("No documents attached.", at: &cursor)
                } else {
                    for doc in context.documents {
                        let expiry = doc.expiryDate.map { " — Expires \(formatter.string(from: $0))" } ?? ""
                        drawLine("• \(doc.documentType.displayName): \(doc.title)\(expiry)", at: &cursor)
                    }
                }
                cursor += 16

                // Footer
                drawText("This document is generated by Pawly for travel convenience and does not replace official regulatory paperwork.",
                         at: cursor, font: .systemFont(ofSize: 10), color: .gray, align: .center)
            }
            return tempURL
        } catch {
            return nil
        }
    }

    // MARK: - Drawing helpers

    private static func drawText(_ text: String, at y: CGFloat, font: UIFont, color: UIColor = .black, align: NSTextAlignment = .left) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = align
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
            .paragraphStyle: paragraph
        ]
        let rect = CGRect(x: 40, y: y, width: 532, height: 40)
        text.draw(with: rect, options: .usesLineFragmentOrigin, attributes: attributes, context: nil)
    }

    private static func drawSection(_ title: String, at cursor: inout CGFloat) {
        drawText(title, at: cursor, font: .systemFont(ofSize: 16, weight: .semibold), color: UIColor(PawlyColors.forest))
        cursor += 22
    }

    private static func drawLine(_ text: String, at cursor: inout CGFloat) {
        drawText(text, at: cursor, font: .systemFont(ofSize: 13))
        cursor += 18
    }
}
